#!/bin/sh
set -eu

printf 'cwd: %s\n' "$(pwd)"

: "${LOCALCI_TASK_OUTPUT_DIR:?}"
: "${LOCALCI_TASK_CACHE_DIR:?}"
: "${LOCALCI_CACHE_DIR:?}"

mkdir -p "$LOCALCI_TASK_OUTPUT_DIR" "$LOCALCI_TASK_CACHE_DIR" "$LOCALCI_CACHE_DIR"
bin_dir="$LOCALCI_TASK_OUTPUT_DIR/bin"

mise run //:web-embed

printf 'go build -o %s ./cmd/localci\n' "$bin_dir/localci"

mkdir -p "$bin_dir"

go build -o "$bin_dir/localci" ./cmd/localci

exit 0
