#!/bin/sh
set -eu

: "${LOCALCI_TASK_OUTPUT_DIR:?}"
: "${LOCALCI_TASK_CACHE_DIR:?}"
: "${LOCALCI_CACHE_DIR:?}"

mkdir -p "$LOCALCI_TASK_OUTPUT_DIR" "$LOCALCI_TASK_CACHE_DIR" "$LOCALCI_CACHE_DIR"

printf 'go test ./...\n'

if go test ./...; then
  exit 0
fi

exit 1
