#!/bin/sh
set -eu

: "${LOCALCI_TASK_OUTPUT_DIR:?}"
: "${LOCALCI_TASK_CACHE_DIR:?}"
: "${LOCALCI_CACHE_DIR:?}"

mkdir -p "$LOCALCI_TASK_OUTPUT_DIR" "$LOCALCI_TASK_CACHE_DIR" "$LOCALCI_CACHE_DIR"

status_file="$LOCALCI_TASK_OUTPUT_DIR/status.txt"

printf 'running\n' >"$status_file"
printf 'running go test ./...\n' >"$LOCALCI_TASK_OUTPUT_DIR/summary.txt"
printf 'go test ./...\n'

if go test ./...; then
  printf 'succeeded\n' >"$status_file"
  exit 0
fi

printf 'failed\n' >"$status_file"
exit 1
