#!/bin/sh
set -eu

printf 'cwd: %s\n' "$(pwd)"

case "${1:-}" in
  ""|--*)
    exec go run ./cmd/localci wait "$@"
    ;;
  *)
    commit=$1
    shift
    exec go run ./cmd/localci wait --commit "$commit" "$@"
    ;;
esac
